version: '3.5'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /opt/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - 9090:9090

  influxdb2:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - /opt/docker/influx/data:/var/lib/influxdb2
      - /opt/docker/influx/config:/etc/influxdb2

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - /opt/docker/grafana:/var/lib/grafana
    depends_on:
      - influxdb2
