global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

rule_files:
  - "alertrules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pfSense'
    static_configs:
      - targets: ['pfSense:9100']
        
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']

  - job_name: 'octoprint'
    scrape_interval: 5s
    metrics_path: '/plugin/prometheus_exporter/metrics'
    params:
      apikey: ['<API KEY>']
    static_configs:
      - targets: ['octopi:80']

  - job_name: 'Electrs'
    static_configs:
      - targets: ['electrs:4224']
